### ISSUE TITLE
Download Zenus data for other than Bundesland 

### ISSUE THREAD

**Issue by chesselingfm** [CorrelAid/pystatis#104]
Hi,
I was wondering if I can download data for a different regional scope than the default "Bundesland" resolution. On the web, I can choose to download data for 1000A-1004 for "Gemeinden". Is that possible? 
Another thing: When displaying the table in the current form, there is no distinction between the full number and the percentage. I guess the rawdata is not parsed correctly. Or am I missing something?
<img width="524" alt="Bildschirmfoto 2024-05-15 um 16 26 52" src="https://github.com/CorrelAid/pystatis/assets/62104097/1d7ea885-e48c-4dfd-a7af-7e0b393639dc">

**Comment by pmayd** [comment]
Hi @chesselingfm, 
I will come back to you a little later but the problem with multiple values in the same column is already fixed in dev, we are actively working at parsing the new data format only available in Zensus. My latest PR should fix the issue (without addressing the language selection, yet, so only for de). Zensus changed to a new format where multiple values are all gathered in a single value column which means that one observation has X rows, one for each value (long format instead of wide). We decided to transform the data so that the user gets back a wide format as it should be, meaning that a single row stands for all observations for that particular identity (unique set of statistic, time, zone and available attributes). 

To your first question: I am sure that is possible and we should already support this because you can pass any keyword argument to the `get_data` method that is supported by the API but I also saw this possibility in the Web UI so I will dig a little deeper and add it in an appropriate way!

**Comment by pmayd** [comment]
Here is your example table with the current dev version:

'|    | Stichtag   | Bundesländer       | Alter (5er-Jahresgruppen)   | Personen__%   |   Personen__Anzahl |\n|---:|:-----------|:-------------------|:----------------------------|:--------------|-------------------:|\n|  0 | 2011-05-09 | Schleswig-Holstein | Insgesamt                   | 100,0         |            2800119 |\n|  1 | 2011-05-09 | Schleswig-Holstein | Unter 5 Jahre               | 4,0           |             112644 |\n|  2 | 2011-05-09 | Schleswig-Holstein | 5 bis 9 Jahre               | 4,5           |             126157 |\n|  3 | 2011-05-09 | Schleswig-Holstein | 10 bis 14 Jahre             | 5,3           |             149131 |\n|  4 | 2011-05-09 | Schleswig-Holstein | 15 bis 19 Jahre             | 5,4           |             151155 |'

As you can see, the previous value column actually combined two observations: "Personen" as count and as percentage. The general way we are handling this in a standardized way for all supported databases is this:
- we always use the attribute label as column name, "Personen" in this case
- we add the unit for this column with a double underscore, so "__Anzahl" and "__%" in this case

This should give you all the information you need as user to work with this column and understand its content

**Comment by pmayd** [comment]
@chesselingfm I just realized we already support your request in the current `dev` branch with the keyword parameters `regionalvariable` and `regionalkey` for `Table.get_data()`. So for any Regionalstatistik table ending with a "B" in its number/name, you can use `regionalvariable` to specify the regional depth. Regionalstatistik supports the follow codes:

- "DG" (Deutschland, 1)
- "DLAND" (Bundesländer, 16)
- "REGBEZ" (Regierungsbezirke, 44)
- "KREISE" (Kreise und kreisfreie Städte, 489)
- "GEMEIN" (Gemeinden, 13564)

However, not every table supports every code/regional depth.

With our next release 0.3.0 this will be part of the master branch and the version that you can install with `pip`. The release will happen somewhere in the next week.

**Comment by pmayd** [comment]
Implemented and documented, see latest release 0.3.0 and the changelog as well as the improved documentation
