### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by chesselingfm** [CorrelAid/pystatis#49]
First of all: Thank you for all the work you have put into this! The API wrapper is very helpful.

I did some test driving and came across some issues. Maybe it's a personal problem or I haven't read the doc properly - forgive me for that ;)

1.) I had to pip install it using --no-dependencies, because my current pandas version is much newer (2.2.0) than the dependency pandas<2.0.0,>=1.4.3

2.)  trying 
```
tabelle = Table(name='81000-0001') 
tabelle.get_data(str="all") 
```
Problem: I only get results from 2014 until now - like the web export from Genesis online. But there is data back to the year 1991. How to retrieve it?

3.) The wrapper is downloading data in the German format (commas as decimals etc.) - so pandas doesn't recognize the columns as numbers. We would have to do it manually. Would it be possible to pass arguments similar to `pd.read_csv(decimals=",", thousands=".")` And have missing values as NaN instead of "-"? If I remember correctly, Michael said something about an English API endpoint that delivers data in a format that works better for pandas.

So, those are my observations, but again: sorry if I was too stupid to find the correct way in the docs and notebooks.

**Comment by bergnerjonas** [comment]
Hi @chesselingfm , thanks for your feedback!
Regarding your questions:
1) The current dependency constraint (pandas = "^2.0") actually dicates a version of pandas >=2.0. Could you try installing the package again, and make sure that you use a fresh virtual environment?
2) You can bypass this by directly passing the startyear argument to your get_data method, such as:
```
table = Table(name='81000-0001') 
table.get_data(startyear="2000") 
```
3) You can theoretically pass the parameter "language" to the get_data method. However, this currently returns an error.

**Comment by chesselingfm** [comment]
Hi, with very large tables, is there the chance to also filter by Monat? And is there also "endyear"? E.g. I have trouble downloading 51000-0014 because of the large size.

**Comment by pmayd** [comment]
Hi @chesselingfm 

Yes, if you use the current dev version, we have described the parameters in detail [here](https://correlaid.github.io/pystatis/dev/pystatis.html#pystatis.table.Table.get_data). There is both `startyear` and `endyear`. As far as I know you cannot limit to a certain month unless the time variable itself is structured in that way, meaning it represents month. However, you can also use `timeslices` instead of `startyear` and `endyear`, which basically is the same as saying you want N years. 

Anyway, our library should also handle background jobs, so normally when you request a table that is too big to be directly avaiable, our library is starting a background process and asks every few seconds if the job is done so we can download the final table. This all happens automatically behind the scenes, so you as a user just have to wait until `get_data` finishes.

I tried the table you mentioned and indeed it seems that in this case the job takes longer than our internal timeout. Maybe we can provide a parameter `timeout` that can be used to wait longer. Normally, `pystatis` is informing you that the table is too big to be downloaded directly and that it will start a background job. Then you just have to wait a few minutes longer, and the table is finally available and returned. There is indeed an internal timeout so if the background job is taking too long, we abort the request and return an error. And this is happening in this case for me as well. 

As far as I know, the whole handling of background jobs should go away once the new format from the Zensus database is rolled out for the other databases, as the new API is always returning zip files which are much smaller

**Comment by pmayd** [comment]
But I just notice in this case there is another error happening ,the problem is not the timeout as this is set to 3000 seconds and if it is exceeded we would print "Timeout exeeded" so here we have another problem. I will investigate. It is a timeout but not on our side, it seems we have a timeout in another requests wheere the default timeout of `requests` library is hitting us

**Comment by pmayd** [comment]
Ah that is interesting, the job actually finished but the very last request downloading the final table is set to a timeout of 60 seconds, which makes no sense as in this case the table is really big and likely takes longer to be downloaded....so I will increase this and the error should be gone

**Comment by pmayd** [comment]
Ok fun, Genesis has changed the API. If you start a job you get a job id but as long as the job is still in processing ,the API returns an error code that the object does not exist. This is not the intended behavior as previously we received a different code indicating that the job is still processing. That is why even with a bigger timeout the function currently does not work...but this is a problem on GENESIS API side and hard to fix for us. I will send them an email with the problem!

**Comment by pmayd** [comment]
Anyway as a workaround I will still implement a fix that will solve this problem

**Comment by pmayd** [comment]
Yep we have an error in our logic, I will push a fix, thanks for pointing that out

**Comment by pmayd** [comment]
OK it was a typical race condition error: Genesis was returning job finished but we started downloading the data a little to soon it seemed as the job was not actually available to be downloaded. A simple sleep between getting the job finish status and starting the download solved this problem, the fix is now available in latest dev so you can try again

**Comment by chesselingfm** [comment]
Thank you for the quick replies! I'll test and report back

**Comment by pmayd** [comment]
@chesselingfm would you also be so kind to test the latest release 0.3.0? It should have all of your latest requests ;) Thanks for your ongoing feedback and feature suggestions
