### ISSUE TITLE
Installing pystatis reverts Pandas from 2.1.1 to 1.5.3

### ISSUE THREAD

**Issue by wahlatlas** [CorrelAid/pystatis#6]
Not sure if this is expected behaviour or I have my dependencies wrong:
When using `pip install pystatis` in a Conda controlled environment containing Python 3.11 and Pandas 2.1.1 my Pandas installation was downgraded in the process to 1.5.3

**Comment by pmayd** [comment]
Every Python project has pinned the dependencies to certain fixed versions, otherwise maintainers cannot guarantee that the library is still working with newer version. Normally we allow some slack by specifying not a fixed version but some freedom for minor version upgrades (that is what "^" usually means in poetry). 

As this project is set up with `poetry`, you have to study the `pyproject.toml` file to see how the dependencies are specified.

And as you can see, all the years back I specified the [following](https://github.com/CorrelAid/pystatis/blob/main/pyproject.toml#L40). So indeed the version is pinned to be not higher than 1 because `^1.4.3` does not allow to fetch a major version update and yes that is exactly what is expected.

If we want to update to a major new version, we can easily do so, simply update the `pyproject.toml` file! **BUT** this means to carefully and thoroughly check the new pandas' API and see if the major version update changed any behavior that we are relying on or if there are any breaking changes. At least all tests should still be green, of course. Then, in principle, nothing speaks against updating pandas.

**Comment by pmayd** [comment]
Thanks for the comment, fixed in version 0.2.0
